brands/urls.py
from django.urls import path
from brands import views

app_name = "brands"

urlpatterns = (
    path('', views.BrandsList.as_view(), name='list'),
    path('<int:pk>/', views.BrandsDetail.as_view(), name='detail'),
)

config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (
    path,
    include,
)
from config import settings
from pages.views import PagesDetail

admin.site.site_header = "PicoStyle management"

# Handle custom error pages
handler404 = 'main.views.page_not_found'
handler500 = 'main.views.server_error'

urlpatterns = []

urlpatterns += i18n_patterns(
    path('account/', include('account.urls')),
    path('news/', include('news.urls')),
    path('brands/', include('brands.urls')),
    path('entrepreneurs/', include('entrepreneur.urls')),
    path('products/', include('products.urls')),
    path('favorites/', include('favorite.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('main.urls')),
    path('pico-style/', admin.site.urls),
    # Pages sections
    path('<str:slug>', PagesDetail.as_view(), name="pages"),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

entrepreneur/urls.py
from django.urls import path
from entrepreneur import views

app_name = "entrepreneur"

urlpatterns = (
    path('', views.EntrepreneursList.as_view(), name='list'),
    path('e/<int:pk>/', views.EntrepreneursDetail.as_view(), name='detail'),
)

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = (
    path('', views.Index.as_view(), name='index'),
    path('change-lang', views.change_lang, name='change_lang'),
    # retailer
    path('become-retailer', views.BecomeRetailer.as_view(), name='become_retailer'),
    path('thanks', views.thanks, name='thanks'),
    # store and agent
    path('store-and-agent', views.store_agent, name='store_agent'),
    # Size guide
    path('size-guide/', views.MainSizeGuide.as_view(), name='size_guide'),
    path('size-guide/women/', views.SizeGuideWomen.as_view(), name='sg_women'),
    path('size-guide/men/', views.SizeGuideMen.as_view(), name='sg_men'),
    # Work with us
    path('work-with-us/', views.WorkWithUsList.as_view(), name='work_with_us'),
    # Special projects
    path('special-projects/', views.SpecialProjectsList.as_view(), name='special_projects'),
)

brands/models.py
from django.db import models

brands/views.py
from django.shortcuts import get_object_or_404
from django.views import generic
from account.models import User


# view for show of brands
class BrandsList(generic.ListView):
    """
    List of brands
    """
    template_name = 'brands/pages/list.html'
    paginate_by = 12
    context_object_name = "brands"
    queryset = User.objects.get_brands()


class BrandsDetail(generic.DetailView):
    """
    Detail brands
    """
    context_object_name = "brand"
    template_name = 'brands/pages/detail.html'

    def get_object(self, queryset=None):
        return get_object_or_404(User, pk=self.kwargs['pk'])

brands/templates/brands/pages/detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
{{ brand }} | PicoStyle
{% endblock title %}

{% block main %}
<div class="container detail">
    <div class="my-5">
        <div class="row">
            <div class="col-12">
                <a href="javascript:history.back()" class="back-btn">
                    <i class="fa fa-arrow-left"></i> {% translate 'back' %}
                </a>
                <img src="{{ brand.brand_logo.url }}" alt="{{ brand.brand_name }}" class="brands-image">
                <h3 class="news-title">{{ brand.brand_name }}</h3>
                <hr>
            </div>
            <div class="col-12 mt-4">
                {{ brand.about_brand|safe }}
            </div>
        </div>
    </div>
</div>
{% endblock main %}

brands/templates/brands/pages/list.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% block title %}
    {% translate 'Brands' %} | PicoStyle
{% endblock title %}

{% block main %}
    <div class="container-fluid">
        <div class="row" style="background: #edf1f7;">
            <!-- Sidebar -->
            <div class="col-md-3 col-12 position-relative hide-mo" style="max-width: 22% !important;">
                <div class="d-flex flex-column flex-shrink-0 p-3 bg-light shadow-sm position-absolute"
                     style="width: 260px; top: 0; bottom: 0; left: 0;">
                    <div class="side-nav-categories">
                        <div class="category-title">
                            <strong> {% translate 'Categories' %} </strong>
                        </div>
                        <ul id="cat">
                            <li>
                                <a href="{% url 'brands:list' %}"
                                   class="main-category active">
                                    {% translate 'Brands' %}
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'entrepreneur:list' %}"
                                   class="main-category">
                                    {% translate 'Entrepreneurs' %}
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-9 col-12 my-5 mt-7">
                <div class="row">
                    <div class="col-12">
                        <h2>
                            {% translate 'Brands' %}
                        </h2>
                    </div>
                    {% for brand in brands %}
                        <div class="col-md-3 col-6">
                            <div class="product-card"
                                 style="padding: 5px; background-color: #fff; box-shadow: 2px 2px 5px #00000037">
                                <a href="{% url 'brands:detail' pk=brand.pk %}">
                                    <img class="product-img" src="{{ brand.brand_logo.url }}"
                                         alt="{{ brand.brand_name }}"
                                         loading="lazy" style="object-fit: scale-down">
                                </a>
                                <div class="p-2">
                                    <div class="product-title">
                                        <a href="{% url 'brands:detail' pk=brand.pk %}">
                                            {{ brand.brand_name }}
                                        </a>
                                    </div>
                                    <a href="{{ brand.get_absolute_url }}">
                                        {% translate 'Read more...' %}
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <div class="col-12 text-center my-4">
                            <h3>
                                {% translate 'There are currently no News' %}
                            </h3>
                        </div>
                    {% endfor %}
                </div>
                <div class="row">
                    <div class="col-12 d-flex justify-content-center">
                        <nav>
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                           aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                            <span class="sr-only">{% translate 'Previous' %}</span>
                                        </a>
                                    </li>
                                {% endif %}
                                {% for page in page_obj.paginator.page_range %}
                                    {% if page_obj.number == page %}
                                        <li class="page-item active">
                                            <a class="page-link" href="javascript:void(0)">{{ page }}</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}"
                                           aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                            <span class="sr-only">{% translate 'Next' %}</span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}